dist: xenial
language: node_js
node_js:
  - lts/*
  - node
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  app: abbas-yadollahi
  api_key:
    secure: XAxSgFwMiffT10Ja83yIF6EneDuL1Q+RXc8HoAXkl6JCokKdcgWNf3kPXKk/h8biH17JI7oLe43w1rYZG2QwlkOSCsGy5gqhjNpn/dKDLlmYiax6CzSTl+vhqhNDzhy22xFfylxmmEyWbG/pa2e5+jnfsezSUghwfVsNL6EDOyOpL2L8k+weu8PNITKvQqf20GW9EeZ9/2dDo9Tud1+WtDorWZy+364DEpcQiM6fz85DkiLaZlcnt3VoMtNpmCrmCsgApkY5Opki6y/y+8/FzRStt2o8VsPitoalV/p3jpPY8NZn2Zh8Awtkuw2zSECs1Z3C1TGgNkB4wCWVMAcJ97e60IqH6Chf2aZPGHrWjA1U3i7x/DgAMeuWoxTYXDYrZ+e5OESdds1ClwpBNyOH7V8jSxwjyPuEdDDy8BoKvEsTdrKlh+p1EaI4dbAbZw3eUztYjlS4qjxRxkVLEXSNXR+JmNkgy3dXkNJI+yRHjweoZQK1H4Uds36nwgSHLDFUzAoqYHaJdCCZscoi4H19zUUC1HxSWER4L35L+wzvfIqeNN5+8vbJYDIRvEF+jGvmvfe196eXXX5td+OP8XaMLcpj5rrdHm6V74kRAI2uC21/uU+wWXr5auwJJzB8tgakO2Hisef2OgYQTYfj2pZq4lSXag2eF4vSfsmvYyqHCuw=
  on:
    repo: theGirrafish/abbas-yadollahi
