dist: xenial
language: node_js
node_js:
  - lts/*
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
deploy:
  provider: heroku
  app: abbas-yadollahi
  api_key:
    secure: JnSDL0Hi6AgxB0KIMib4+SasnFjLO8hGifHsF98dTMfLxNWlpsk/9RkH7264edeMJWSdfix4+u4ctwlSaPOtoX9k47XQVud86/f2BhRMq7sCsi3GaGZEL2FALz1OWBijQgWeIc9aT1pkfW8VZPpbpGaq5nAhBUxPu4k7ytkZ9iQKfqeiZCzvWlEy9LLFB19KF9zyHkq8aWm23HHmzPwfbjoLusZA5CUAvrhYlS89v0JLRGXyNKFYO/xiqP6AsVQEtYJ7UVFsBsY5eBv7rjSjPwsxKTq+SGD/xzOAT3Fwzk36TuXlniSkMg25niW8UP2/WfCCQVdb7e5LCR3Bp3MOqk0S/dw0EPvOB6fuqJIbUlkg/AR4YeJX1b8d/Jfncxw+8zpPmDR+ERNocHDqVEOEGqDQvmqZn8LdZ5EyPYHoOwoa3HKx9wAkky3+PW9oS44lPrZfuVuY7l+LbmgPkFuC8dekO1QHtx1LVClg331MJOBkR6EP2B7cq0kqe/xVhpqkS1w4o70yJPROwEOK17AWLXWznFObC/fl68gPeJhnQvlgDnnbh2Ou02zLJAly/sUWRlnvSRQVk/QHePqbUuMAzKNgMuL+AsOqAlJ09yrrQGro+xftC2RXZ9A9lgYxUrrdz+TAnFlcplstSCrIOitotkgH8MED1Qs3vc2xm/A0xM8=
  on:
    repo: theGirrafish/abbas-yadollahi
