dist: xenial
language: node_js
node_js:
  - lts/*
  - node
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  app: abbas-yadollahi
  api_key:
    secure: DUf3HZabcX0wn66EbZtFgPXmBt4cNmUNfr+9bXuT2JbJcIDr0ZAEmvsj726O1sBZgxsbec9Oq2b9VmTxn9V5870plJBkunSFX9Pohi0g3KLZ8VKiXij29Qk5BKBqxk8udHR+UTidJxcdvNB0chbGbAa1JZeJ+dQ2ZBw95OF6JTXS/gme9YAsJ9CEP7X7L2WokQ/teseeHHc5CpyJFDLUBvvW308M4Z+9lQyRb7AV2clAVJad2GVdNLxBwAmAL3TzOpdqxT2XpfvZI7rQYtmcHD+mtxHr0Ox/GLe2rsRlT1DEA6FVVwA7uEyX1WnuhXEW6HrUljtRLRkA+TjroSWctnePpISRtGvRbs68Vk+t39xFYAYlhcRxOdd0xB3SISHQm8LfGR3/9HUSX92Ufxb8Hjnr4DB3b15ghiE/d4r0wKy9xsH/4otz+KLYHZjlprcr9f0uXux5/vGm/G08JkIOrbzHYPN2VRYyxR+3zsBKpPC+M3E2m9P1XPMCl0PNh/4AEf4ipg/eHV7BKRv77R01YhRWyYWONQmyYur6NyCXwpwsmddPGOt8SU0dIr0Opjo/dMEWsH1DWg+mELwdRfK4IfV7lM4EvZcwQ0gxntlK9n3vYPd/+4TMunVOKHN9QbsRLwbgsofqyIdk9bd2w7iXpwFIiOjAkLBTzAuuGvoo4sg=
  on:
    repo: theGirrafish/abbas-yadollahi
